### ISSUE TITLE
Server Request 

### ISSUE THREAD

**Issue by arjung24** [sunecz/Media-Downloader#1]
Is it possible to add Hotstar.com and zee5.com content downloading??

**Comment by arjung24** [comment]
Do u have any other way to contact. Like telegram. We can talk about this issue there??

**Comment by arjung24** [comment]
> 

Yes. They are subscription-only sites with DRM-protected content.

**Comment by sunecz** [comment]
I currently don't have setup such communication channels. If you want to contact me, please use my email address, you can see it on my profile page here on GitHub. Thank you.
