### ISSUE TITLE
Česká televize - stahuje se desetisekundové video s varováním místo aktuálního videa

### ISSUE THREAD

**Issue by nemecr** [sunecz/Media-Downloader#10]
Např. https://www.ceskatelevize.cz/porady/1052441871-pernikova-vez/

**Comment by sunecz** [comment]
Díky za nahlášení, opravím to.

**Comment by sunecz** [comment]
@nemecr Aktualizoval jsem plugin pro web České televize, kde se již varování ignoruje a stáhne se tak doopravdy daný film. Stačí jen spustit program.
