### ISSUE TITLE
Ubuntu ARM nelze spustit

### ISSUE THREAD

**Issue by leodog256** [sunecz/Media-Downloader#11]
Je možné spustit tento program na ARM procesoru? Popřípadě jak.

**Comment by sunecz** [comment]
Zdravím, mělo by to být možné.

Níže zasílám instrukce (jako skript) k rozběhnutí programu na ARM Ubuntu. Nemám ale momentálně takto rychle možnost, jak to vyzkoušet. Nepodařilo se mi totiž rozběhnout ARM Ubuntu na QEMU. Když ale vyměním URL ve skriptu za URL pro x86_64/amd64 verze, tak to funguje bez problému.

Mělo by stačit spustit následující skript:
```bash
#!/bin/bash

# Install required tools
sudo apt install -y wget build-essential cmake

# Prepare directory structure
mkdir -p jre/ resources/binary/drm/

# Download JRE
cd jre/
wget -O jre.tar.gz https://download.bell-sw.com/java/11.0.22+12/bellsoft-jre11.0.22+12-linux-aarch64-full.tar.gz
tar --strip-components=1 -xzf jre.tar.gz
rm -f jre.tar.gz
cd ../

# Download FFmpeg
cd resources/binary/
wget -O ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz
tar --strip-components=1 -xJf ffmpeg.tar.xz --wildcards '*/ffmpeg' '*/ffprobe'
rm -f ffmpeg.tar.xz
cd ../../

# Download mp4decrypt
cd resources/binary/drm/
git clone https://github.com/axiomatic-systems/Bento4.git
cd Bento4
mkdir cmakebuild
cd cmakebuild
cmake -DCMAKE_BUILD_TYPE=Release ..
make mp4decrypt
mv mp4decrypt ../../
cd ../../
rm -rf Bento4/
cd ../../../

# Download app
wget https://github.com/sunecz/Media-Downloader/releases/download/v00.02.09-dev.22/media-downloader.jar
echo '{jre:"07.00.00",res_ffmpeg:"05.00.01",res_ffprobe:"05.00.01",drm_res:"08.00.00"}' > resources/versions.ssdf
```

Poznámky:
- Je nutné použít nějakou JRE s JavaFX, tady jsem použil [Liberica JDK pro Java 11](https://bell-sw.com/pages/downloads/#jdk-11-lts)
- FFmpeg je k dispozici pro ARM přes oficiální web, odkaz [Linux static builds](https://johnvansickle.com/ffmpeg/).
- mp4decrypt pro ARM se musí zkompilovat ze [zdrojového kódu](https://github.com/axiomatic-systems/Bento4).
- Stáhne se poslední předběžná verze programu (00.02.09-dev.22).
- Aby se nestahovaly žádné verze JRE/ffmpeg/ffprobe/mp4decrypt pro ne-ARM operační systém, musí se vytvořit soubor resources/versions.ssdf s již předvyplněnými hodnotami.

Poté stačí už jen:
```
jre/bin/java -jar media-downloader.jar
```

Řádná podpora pro ARM operační systémy bude v dalších verzích, momentálě je nutné to takto trochu obejít.

Dejte když tak prosím vědět, jestli to funguje.

**Comment by leodog256** [comment]
Zdravím,
děkuji za vyčerpávající odpověď. Vše funguje jak má.

**Comment by sunecz** [comment]
Super, díky za potvrzení :)
