### ISSUE TITLE
Voyo - hlášení "Nebyly nalezeny žádné mediální zdroje"

### ISSUE THREAD

**Issue by Jenikcz** [sunecz/Media-Downloader#14]
Dobrý den,

Na webu Voyo dnes (včera vše fungovalo) po výběru pořadu a po zvolení epizody program nevyhledá mediální zdroje a nahlásí "Nebyly nalezeny žádné mediální zdroje".

Děkuji

**Comment by sunecz** [comment]
Dobrý den, získávání zdrojů jsem opravil. Pokud máte zapnuté automatické aktualizace pluginů, stačí jen spustit program.

**Comment by Jenikcz** [comment]
Dobrý den,

Děkuji za opravu, chtěl bych Vás požádat o menší vysvětlení co bylo na webu změněno, že program resp získávání zdrojů nefungovalo (já jsem si všiml, že byl změněn vzhled přehrávače Voyo) .

Ještě menší nedostatek v programu weby tv.nova.cz a iprima, když si vyberu pořad tak při výběru mediálních souborů/kvality mi to najde soubory DASH a M3U8 ale když zvolím M3U8 tak stahování nedokončí postup, zůstanou dva soubory video a audio bez sloučení. 

Dále, je možné získat na Vás kontakt přes email, chtěl bych se Vás na něco zeptat přes programování.

Děkuji.

**Comment by sunecz** [comment]
Dobrý den,

v embedu přehrávače změnili strukturu, konkrétně především obsah skriptu, ve kterém se nachází nastavení pro přehrávač, a tudíž i URL pro samotné zdroje (M3U8/MPD). Konkrétní změny můžete nalézt v příslušném commitu: https://github.com/sunecz/Media-Downloader-Default-Plugins/commit/d3ea57f924b19f047e8394fcf2fcc2894aa8e135

Každopádně existuje i API, o kterém jsem do nedávna nevěděl, které vůbec nevyužívá extrakci ze stránek, ale jedná se o takové REST API. Mám v plánu na něj v blízké době přejít.

E-mail na mě můžete nalézt v mém profilu tady na GitHubu (https://github.com/sunecz).
