### ISSUE TITLE
Voyo SK - hlášení "Nebyly nalezeny žádné mediální zdroje"

### ISSUE THREAD

**Issue by Jenikcz** [sunecz/Media-Downloader#15]
Dobrý den,

Na webu Voyo SK dnes (včera vše fungovalo) po výběru pořadu a po zvolení epizody program nevyhledá mediální zdroje a nahlásí "Nebyly nalezeny žádné mediální zdroje".

Děkuji

**Comment by HarmonyIgor** [comment]
Zdravím, hlásim ten istý problem, vcera fungovalo dnes už nie.
Dakujem za rýchle vyriesenie,  

PS: super program,dakujem

**Comment by sunecz** [comment]
Zdravím,

vydal jsem novou verzi pluginu pro Voyo Markíza. Pokud máte zapnuté automatické aktualizace pluginů, stačí jen spustit program. Případně jsou změny pushnuté zde: https://github.com/sunecz/Media-Downloader-Default-Plugins

S pozdravem,
Sune

**Comment by HarmonyIgor** [comment]
Super, ste super rýchli, ďakujem
