### ISSUE TITLE
Doplnění formátu ts

### ISSUE THREAD

**Issue by Jenikcz** [sunecz/Media-Downloader#3]
Dobrý den,

Mám na Vás menší žádost, je možné doplnit volbu výstupního videa ve formátu ts.

Děkuji

**Comment by sunecz** [comment]
Dobrý den,

není problém, přidám to v další verzi.

Jen abych se ujistil, chcete přímo ukládat raw stream HLS segmentů, tj. jakoby jen spojovat .ts soubory? Nebo to má mít jiné využití? Děkuji předem za doplnění.

**Comment by Jenikcz** [comment]
Dobrý den,

Já mám na mysli, když si vyhledám díl seriálu ke stažení a vyberu si ho, zvolím kvalitu - tabulka "Vybrat mediální zdroj" pak je tabulka "Nastavení stahování" a "Výstupní formát" a vybírá se z formátů jako MP4, FLV, AVI, MKV, WMV atd., tak mít možnost vybrat i formát .ts

Děkuji

**Comment by sunecz** [comment]
Dobrý den, výstupní formát .ts je nyní dostupný v poslední předběžné verzi 00.02.09-dev.18.
